- name:  Prepare Various Images required for Installation
  hosts: localhost
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Add all hypervisor group-host
    add_host:
      name: "{{ item.hypervisor_name }}"
      ansible_ssh_user: "{{ item.hypervisor_user }}"
      ansible_ssh_private_key_file: "{{ item.hypervisor_ssh_key }}"
      groups:
        - hypervisor_host
    with_items: "{{ undercloud_nodes }}"
    when: item.hypervisor_name != "localhost"

- name:  Build controller hosts
  hosts:
    - localhost
    - hypervisor_host
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Copying RHEL-8 Image from web to images dir
    get_url:
      url: "{{ image_location }}"
      dest: "{{ item.hypervisor_image_dir }}/{{ supported_os }}.qcow2"
      mode: '0660'
      owner: root
      group: root
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ undercloud_nodes }}"

  - name: Create a new 100GB Blank Image
    shell: |
      qemu-img create -f qcow2  {{ item.hypervisor_image_dir }}/{{ supported_os }}-100G.qcow2 100G
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ undercloud_nodes }}"

  - name: Resizing the filesystem to 100G
    shell: |
      virt-resize --expand /dev/sda1 {{ item.hypervisor_image_dir }}/{{ supported_os }}.qcow2 {{ item.hypervisor_image_dir }}/{{ supported_os }}-100G.qcow2
    environment:
      LIBGUESTFS_PATH: "{{ libguestfs_path }}"
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ undercloud_nodes }}"

  - name: Customizing the image to set root password, push ssh key and remove cloud-init
    shell: |
      virt-customize -a {{ item.hypervisor_image_dir }}/{{ supported_os }}-100G.qcow2 --root-password password:"{{ secure_password }}" --ssh-inject "root:file:{{ ssh_pub }}" --selinux-relabel --run-command 'yum remove cloud-init* -y'
    environment:
      LIBGUESTFS_PATH: "{{ libguestfs_path }}"
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ undercloud_nodes }}"

- name:  Prepare Undercloud Golden Image for OSP-16
  hosts:
    - localhost
    - hypervisor_host
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Copy Base Image to create Undercloud image
    copy:
      src: "{{ item.hypervisor_image_dir }}/{{ supported_os }}-100G.qcow2"
      dest: "{{ item.hypervisor_image_dir }}/{{ supported_os }}-undercloud.qcow2"
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ undercloud_nodes }}"

  - name: Create /tmp/ifcfg-eth0 for RHEL8
    copy:
      dest: /tmp/ifcfg-eth0
      mode: '0644'
      content: |
        DEVICE=eth0
        ONBOOT=yes
        IPADDR={{ undercloud_ip }}
        NETMASK=255.255.255.0
        GATEWAY=192.168.122.1
        NM_CONTROLLED=yes
        DNS1={{ dns_ip_undercloud }}
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ undercloud_nodes }}"

  - name: Create /tmp/ifcfg-eth1 for RHEL8
    copy:
      dest: /tmp/ifcfg-eth1
      mode: '0644'
      content: |
        DEVICE=eth1
        TYPE=Ethernet
        IPADDR={{ undercloud_ip_prv }}
        DEFROUTE=no
        NETMASK=255.255.255.0
        ONBOOT=yes
        NM_CONTROLLED=no
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ undercloud_nodes }}"

  - name: Create /tmp/ifcfg-eth1.2002 for RHEL8
    copy:
      dest: "/tmp/ifcfg-eth1.2002"
      mode: '0644'
      content: |
        DEVICE=eth1.2002
        BOOTPROTO=static
        ONBOOT=yes
        IPADDR=192.168.202.30
        NETMASK=255.255.255.0
        DEFROUTE=no
        NM_CONTROLLED=no
        VLAN=yes
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ undercloud_nodes }}"

  - name: Create /tmp/ifcfg-eth1.2003 for RHEL8
    copy:
      dest: "/tmp/ifcfg-eth1.2003"
      mode: '0644'
      content: |
        DEVICE=eth1.2003
        BOOTPROTO=static
        ONBOOT=yes
        IPADDR=192.168.203.30
        NETMASK=255.255.255.0
        DEFROUTE=no
        NM_CONTROLLED=no
        VLAN=yes
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ undercloud_nodes }}"

  - name: Copying Config files to the rhel8 undercloud image
    shell: |
      virt-copy-in -a {{ item.hypervisor_image_dir }}/{{ supported_os }}-undercloud.qcow2 /tmp/ifcfg-eth0 /tmp/ifcfg-eth1 /tmp/ifcfg-eth1.2002 /tmp/ifcfg-eth1.2003 /etc/sysconfig/network-scripts/
    environment:
      LIBGUESTFS_PATH: "{{ libguestfs_path }}"
    delegate_to: "{{ item.hypervisor_name }}"
    run_once: True
    with_items: "{{ undercloud_nodes }}"
